---
environment:
    humanArea: 'humanReachable'
    middleArea: 'secondReachable'
    robotArea: 'robotReachable'
    supportsToPlace: ['PLACEMAT_1', 'PLACEMAT_2', 'PLACEMAT_3', 'PLACEMAT_4', 'PLACEMAT_5', 'PLACEMAT_6', 'PLACEMAT_7']
    objectsToRandomlyPlace: ['GREEN_TAPE1', 'GREEN_TAPE2', 'GREEN_TAPE3', 'BLUE_TAPE1', 'BLUE_TAPE2', 'BLUE_TAPE3']
    objectsPose:
        PLACEMAT_1:
            x: 4.4
            y: 3.6
            z: 0.72
            rotation: false
        PLACEMAT_2:
            x: 4.5
            y: 3.5
            z: 0.72
            rotation: false
        PLACEMAT_3:
            x: 4.7
            y: 3.8
            z: 0.72
            rotation: false
        PLACEMAT_4:
            x: 4.6
            y: 4.3
            z: 0.72
            rotation: false
        PLACEMAT_5:
            x: 4.75
            y: 4.3
            z: 0.72
            rotation: true
        PLACEMAT_6:
            x: 4.8
            y: 4.5
            z: 0.72
            rotation: false
        PLACEMAT_7:
            x: 4.9
            y: 4.6
            z: 0.72
            rotation: false
    locations:
        PLACEMAT_1:
            - 'ROBOT_LOC'
        PLACEMAT_2:
            - 'ROBOT_LOC'
        PLACEMAT_3:
            - 'ROBOT_LOC'
            - 'HUMAN_LOC'
        PLACEMAT_4:
            - 'ROBOT_LOC'
            - 'HUMAN_LOC'
            - 'SECOND_LOC'
        PLACEMAT_5:
            - 'ROBOT_LOC'
            - 'HUMAN_LOC'
            - 'SECOND_LOC'
        PLACEMAT_6:
            - 'HUMAN_LOC'
            - 'SECOND_LOC'
        PLACEMAT_7:
            - 'HUMAN_LOC'
            - 'SECOND_LOC'
